//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDC.LeadCapture.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public long Id { get; set; }
        public long AssessmentQuestionId { get; set; }
        public long QuestionItemId { get; set; }
        public long AnswerChoiceId { get; set; }
        public string Value { get; set; }
        public long ResponseId { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
