//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDC.LeadCapture.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerType
    {
        public AnswerType()
        {
            this.AssessmentAnswerChoice = new HashSet<AssessmentAnswerChoice>();
            this.Question = new HashSet<Question>();
            this.QuestionItem = new HashSet<QuestionItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool MultipleChioce { get; set; }
    
        public virtual ICollection<AssessmentAnswerChoice> AssessmentAnswerChoice { get; set; }
        public virtual ICollection<Question> Question { get; set; }
        public virtual ICollection<QuestionItem> QuestionItem { get; set; }
    }
}
