//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDC.LeadCapture.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AssessmentEntities : DbContext
    {
        public AssessmentEntities()
            : base("name=AssessmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answer { get; set; }
        public virtual DbSet<AnswerChoice> AnswerChoice { get; set; }
        public virtual DbSet<AnswerType> AnswerType { get; set; }
        public virtual DbSet<Assessment> Assessment { get; set; }
        public virtual DbSet<AssessmentAnswerChoice> AssessmentAnswerChoice { get; set; }
        public virtual DbSet<AssessmentQuestion> AssessmentQuestion { get; set; }
        public virtual DbSet<Campaign> Campaign { get; set; }
        public virtual DbSet<Partner> Partner { get; set; }
        public virtual DbSet<PartnerDetails> PartnerDetails { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<QuestionItem> QuestionItem { get; set; }
        public virtual DbSet<Resource> Resource { get; set; }
        public virtual DbSet<ResourceType> ResourceType { get; set; }
        public virtual DbSet<ResourceValue> ResourceValue { get; set; }
        public virtual DbSet<Response> Response { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Section> Section { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UserStatus> UserStatus { get; set; }
        public virtual DbSet<Score> Score { get; set; }
    
        public virtual ObjectResult<string> usp_GetHash(string cleartext)
        {
            var cleartextParameter = cleartext != null ?
                new ObjectParameter("Cleartext", cleartext) :
                new ObjectParameter("Cleartext", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_GetHash", cleartextParameter);
        }
    }
}
