//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDC.LeadCapture.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentAnswerChoice
    {
        public long Id { get; set; }
        public long AssessmentQuestionId { get; set; }
        public string Name { get; set; }
        public int OrderNo { get; set; }
        public Nullable<long> TextId { get; set; }
        public int AnswerTypeId { get; set; }
        public long QuestionItemId { get; set; }
        public long AnswerChoiceId { get; set; }
        public Nullable<long> AltQuestionItemId { get; set; }
        public bool AlternativeAnswer { get; set; }
        public bool Encrypted { get; set; }
        public Nullable<decimal> Score { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Deleted { get; set; }
    
        public virtual AnswerChoice AnswerChoice { get; set; }
        public virtual AnswerType AnswerType { get; set; }
        public virtual AssessmentQuestion AssessmentQuestion { get; set; }
        public virtual QuestionItem QuestionItem { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
