//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDC.LeadCapture.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentQuestion
    {
        public AssessmentQuestion()
        {
            this.AssessmentAnswerChoice = new HashSet<AssessmentAnswerChoice>();
        }
    
        public long Id { get; set; }
        public long AssessmentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int OrderNo { get; set; }
        public Nullable<long> TextId { get; set; }
        public Nullable<long> AltTextId { get; set; }
        public Nullable<long> ValidationTextId { get; set; }
        public int AnswerTypeId { get; set; }
        public Nullable<long> SectionId { get; set; }
        public Nullable<int> PageNo { get; set; }
        public bool QuestionGroup { get; set; }
        public Nullable<long> QuestionGroupId { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Optional { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        public virtual ICollection<AssessmentAnswerChoice> AssessmentAnswerChoice { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual Resource Resource1 { get; set; }
        public virtual Resource Resource2 { get; set; }
        public virtual Section Section { get; set; }
    }
}
