//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDC.LeadCapture.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public Partner()
        {
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> PartnerDetailsId { get; set; }
        public bool Disabled { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual PartnerDetails PartnerDetails { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
