//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDC.LeadCapture.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerDetails
    {
        public PartnerDetails()
        {
            this.Partner = new HashSet<Partner>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string CCEmail { get; set; }
        public string BCCEmail { get; set; }
    
        public virtual ICollection<Partner> Partner { get; set; }
    }
}
