//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDC.LeadCapture.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.QuestionItem = new HashSet<QuestionItem>();
        }
    
        public long Id { get; set; }
        public Nullable<long> ResourceId { get; set; }
        public int AnswerTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual AnswerType AnswerType { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual ICollection<QuestionItem> QuestionItem { get; set; }
    }
}
