//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDC.LeadCapture.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response
    {
        public long Id { get; set; }
        public Nullable<System.Guid> ResponseKey { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public Nullable<long> CampaignId { get; set; }
        public string Email { get; set; }
        public Nullable<int> CompletedPageNo { get; set; }
        public Nullable<int> CompletedQuestionNo { get; set; }
        public bool Completed { get; set; }
        public bool ReportSent { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<System.DateTime> DateReportSent { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public Nullable<long> AssessmentId { get; set; }
        public bool Error { get; set; }
    }
}
