//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDC.LeadCapture.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int Id { get; set; }
        public long ResponseId { get; set; }
        public decimal Overall { get; set; }
        public Nullable<decimal> Domain1 { get; set; }
        public Nullable<decimal> Domain2 { get; set; }
        public Nullable<decimal> Domain3 { get; set; }
        public Nullable<decimal> Domain4 { get; set; }
        public Nullable<decimal> Domain5 { get; set; }
        public Nullable<decimal> Domain6 { get; set; }
        public Nullable<decimal> Domain7 { get; set; }
        public Nullable<decimal> Domain8 { get; set; }
        public Nullable<decimal> Domain9 { get; set; }
        public Nullable<decimal> Domain10 { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
