insert into Resource (Name, [DefaultValue], [ResourceTypeId], [Tag]) values ('PeerScore_Overall_Top10pct', '2.40',  4, 'PeerScoreOverall')

insert into Resource (Name, [DefaultValue], [ResourceTypeId], [Tag]) values ('PeerPct_Overall_Level1', '20',  4, 'PeerPct')
insert into Resource (Name, [DefaultValue], [ResourceTypeId], [Tag]) values ('PeerPct_Overall_Level2', '66',  4, 'PeerPct')
insert into Resource (Name, [DefaultValue], [ResourceTypeId], [Tag]) values ('PeerPct_Overall_Level3', '11',  4, 'PeerPct')
insert into Resource (Name, [DefaultValue], [ResourceTypeId], [Tag]) values ('PeerPct_Overall_Level4', '3',  4, 'PeerPct')

exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Austria', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Finland', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Ireland', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Norway', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'South Africa', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Turkey', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Belgium', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'France', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Italy', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Poland', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Spain', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'United Kingdom', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Denmark', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Germany', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Luxembourg', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Portugal', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Sweden', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Hungary', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Netherlands', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Russia', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Switzerland', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Czech Republic', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Slovakia', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Other - Europe/Middle East/Africa', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.50', 'Canada', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.50', 'United States', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.45', 'Argentina', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.45', 'Chile', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.45', 'Brasil', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.45', 'Peru', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.45', 'Colombia', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.45', 'Panama', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.45', 'Costa Rica', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.45', 'Dominican Republic', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.45', 'Puerto Rico', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.45', 'El Salvador', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.45', 'Mexico', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.45', 'Guatemala', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.45', 'Other- Americas', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Hong Kong', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Japan', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Australia', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Omdoa', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Malaysia', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'New Zeland', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Philippines', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Singapore', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Taiwan', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Thailand', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Vietnam', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Korea', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'China', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_Region_Top10pct', '2.46', 'Other- Asia Pacific', 4, 'PeerScoreRegion'

exec usp_SetResourceValue 'PeerScore_OrgSize_Top10pct', '2.70', 'Fewer than 499 employees', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_OrgSize_Top10pct', '2.57', '500 to 999 employees', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_OrgSize_Top10pct', '2.45', '1,000 to 1,499 employees', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_OrgSize_Top10pct', '2.06', '1,500 to 2,499 employees', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_OrgSize_Top10pct', '2.49', '2,500 to 4,999 employees', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_OrgSize_Top10pct', '2.41', '5,000 to 9,999 employees', 4, 'PeerScoreRegion'
exec usp_SetResourceValue 'PeerScore_OrgSize_Top10pct', '2.42', '10,000 or more employees', 4, 'PeerScoreRegion'

exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.47', 'Banking', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.67', 'Broadcast communications or media', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.48', 'Construction', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.46', 'Consumer or recreational services', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.26', 'Education', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.62', 'Energy or utilities', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.13', 'Government', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.65', 'Healthcare', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.30', 'Information technology', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.35', 'Insurance', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.47', 'Life sciences', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.19', 'Manufacturing', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.09', 'Market research', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.65', 'Professional services', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.64', 'Resource industries', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.47', 'Retail', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.26', 'Securities/financial services', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.28', 'Telecommunications', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.25', 'Transportation', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.30', 'Wholesale trade', 4, 'PeerScoreIndustry'
exec usp_SetResourceValue 'PeerScore_Industry_Top10pct', '2.40', 'Other', 4, 'PeerScoreIndustry'
update Resource set DefaultValue = '2.40' where Name = 'PeerScore_Industry_Top10pct'




